FROM node:18-alpine

WORKDIR /app

COPY .nuxt .nuxt

COPY node_modules node_modules

COPY package.json package.json

COPY nuxt.config.js nuxt.config.js

COPY static static

COPY .env .env

COPY utils utils

ENV NUXT_HOST=0.0.0.0

ENV NUXT_PORT=3000

EXPOSE 3000

CMD ["sh", "-c", "yarn start"]