FROM node:22-alpine

WORKDIR /app

COPY .nuxt .nuxt

COPY node_modules node_modules

COPY package.json package.json

COPY nuxt.config.js nuxt.config.js

COPY static static

COPY modules modules

COPY middleware middleware

COPY utils utils

EXPOSE 3000 8090

CMD ["sh", "-c", "yarn start"]
