FROM node:22-alpine

WORKDIR /app

COPY .nuxt .nuxt

COPY node_modules node_modules

COPY package.json package.json

COPY ssr.nuxt.config.js ssr.nuxt.config.js

COPY static.nuxt.config.js static.nuxt.config.js

COPY static static

COPY modules modules

COPY middleware middleware

COPY utils utils

EXPOSE 3000 8090

CMD ["sh", "-c", "npm run ssr:serve"]
