const fs = require('fs')
const path = require('path')

// Rewrites the SSR host into the static host across the generated bundle: pages are
// generated by hitting the SSR site, so every absolute URL it emitted has to be moved
// onto the public hostname.
//
// Media URLs are deliberately NOT rewritten. They point at web-medias.<zone>, which is
// Cloudflare in front of the GCS bucket the WordPress writes to (wp-stateless), so they
// are already public, cached and correct as they stand. Rewriting them into the bundle
// (which is what the removed API_UPLOADS_URL -> /assets replacement did, together with
// the static-uploads module) meant the build had to download every media and ship it in
// the bundle, and a media added or replaced in the backoffice only appeared online at
// the next deploy.
module.exports = async function module() {
  const nuxtInstance = this
  nuxtInstance.nuxt.hook('generate:done', async () => {

    console.info('Static URL override...');

    const distPath = path.join(__dirname, '../../dist')

    function replaceInFile(filePath) {
      try {
        let content = fs.readFileSync(filePath, 'utf8')
        const originalContent = content

        const ssrOriginalUrl = process.env.SSR_PROTOCOL + '://' + process.env.SSR_HOST;
        const ssrEncodedUrl = ssrOriginalUrl.replaceAll('/', '\\u002F');
        const staticOriginalUrl = process.env.STATIC_PROTOCOL + '://' + process.env.STATIC_HOST;
        const staticEncodedUrl = staticOriginalUrl.replaceAll('/', '\\u002F');
        content = content
          .replaceAll(ssrOriginalUrl, staticOriginalUrl)
          .replaceAll(ssrEncodedUrl, staticEncodedUrl);

        if (content !== originalContent) fs.writeFileSync(filePath, content, 'utf8');

      } catch (error) {
        console.error(`Error processing ${filePath}:`, error)
      }
    }

    function walkDirectory(dir) {
      try {
        const files = fs.readdirSync(dir)
        files.forEach(file => {
          const filePath = path.join(dir, file)
          const stat = fs.statSync(filePath)

          if (stat.isDirectory()) {
            walkDirectory(filePath)
          } else if (stat.isFile()) {
            replaceInFile(filePath)
          }
        })
      } catch (error) {
        console.error(`Error walking directory ${dir}:`, error)
      }
    }

    walkDirectory(distPath)
    console.info('Static URL override complete.')
  })
}
module.exports.meta = require('./package.json')
