const fs = require('fs')
const path = require('path')

// Rewrites two hostnames across the generated bundle.
//
// 1. SSR host -> static host: pages are generated by hitting the SSR site, so every
//    absolute URL it emitted has to be moved onto the public hostname.
//
// 2. Media preview host -> media public host. The backoffice writes its media into the
//    PREVIEW bucket and stores preview URLs (wp-stateless keeps the URL it was given at
//    upload time), so that is what the API serves and what the generator emits. The deploy
//    syncs that bucket into the public one and this rewrite points the bundle at the copy.
//    That indirection is the whole point: it is what makes a media go online when the site
//    is deployed rather than the second it is saved in wp-admin, and it is why the media of
//    a previous bundle survive — the sync only ever adds objects, never deletes, so rolling
//    the Cloudflare worker back to an older bundle finds its images still there.
//    Do NOT rewrite this the other way round in the backoffice: the stored URL is the
//    preview one, the published one is derived here.
//
// Both hosts are replaced in their raw form and in the /-escaped form Nuxt uses inside
// the inlined `window.__NUXT__` payload.
module.exports = async function module() {
  const nuxtInstance = this
  nuxtInstance.nuxt.hook('generate:done', async () => {

    console.info('Static URL override...');

    const distPath = path.join(__dirname, '../../dist')

    const ssrOriginalUrl = process.env.SSR_PROTOCOL + '://' + process.env.SSR_HOST;
    const staticOriginalUrl = process.env.STATIC_PROTOCOL + '://' + process.env.STATIC_HOST;

    // [from, to] pairs. An empty MEDIA_* would turn replaceAll into a rewrite of every
    // position in every file, so the media pair is only added when both are set.
    const replacements = [[ssrOriginalUrl, staticOriginalUrl]]
    if (process.env.MEDIA_PREVIEW_URL && process.env.MEDIA_PUBLIC_URL) {
      replacements.push([process.env.MEDIA_PREVIEW_URL, process.env.MEDIA_PUBLIC_URL])
    } else {
      console.warn('MEDIA_PREVIEW_URL / MEDIA_PUBLIC_URL unset: the bundle will keep pointing at the preview media host.')
    }

    // Same pairs, escaped the way Nuxt serialises URLs into the inlined state.
    const encodedReplacements = replacements.map(
      ([from, to]) => [from.replaceAll('/', '\\u002F'), to.replaceAll('/', '\\u002F')]
    )

    function replaceInFile(filePath) {
      try {
        let content = fs.readFileSync(filePath, 'utf8')
        const originalContent = content

        for (const [from, to] of [...replacements, ...encodedReplacements]) {
          content = content.replaceAll(from, to);
        }

        if (content !== originalContent) fs.writeFileSync(filePath, content, 'utf8');

      } catch (error) {
        console.error(`Error processing ${filePath}:`, error)
      }
    }

    function walkDirectory(dir) {
      try {
        const files = fs.readdirSync(dir)
        files.forEach(file => {
          const filePath = path.join(dir, file)
          const stat = fs.statSync(filePath)

          if (stat.isDirectory()) {
            walkDirectory(filePath)
          } else if (stat.isFile()) {
            replaceInFile(filePath)
          }
        })
      } catch (error) {
        console.error(`Error walking directory ${dir}:`, error)
      }
    }

    walkDirectory(distPath)
    console.info('Static URL override complete.')
  })
}
module.exports.meta = require('./package.json')
