name: continuous-integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  COREPACK_ENABLE_AUTO_PIN: 0
  DOCKER: ""

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-build-${{ github.event.pull_request.number || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron
      - run: make install
      - run: make build
