---
name: release

concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

on:
    push:
        tags: ['*']

env:
    COREPACK_ENABLE_AUTO_PIN: 0
    DOCKER: ''

jobs:
    release:
        runs-on: self-hosted
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/jod
            - name: release
              id: release
              run: |
                  export DOCKER_CONFIG="$(mktemp -d)"
                  echo "DOCKER_CONFIG=${DOCKER_CONFIG}" >> "$GITHUB_ENV"
                  AUTH=$(echo -n "_json_key:$(echo "${KAIKO_GCR_WRITER}" | base64 -d)" | base64 -w0)
                  printf '{"auths":{"gcr.io":{"auth":"%s"}}}\n' "$AUTH" > "$DOCKER_CONFIG/config.json"

                  APP=spininteractive-institutionalwebsite
                  VERSION=$(echo ${GITHUB_REF_NAME} | sed 's#/+#-#g')
                  make release VERSION=${VERSION}
                  docker push gcr.io/kaiko-gcr/$APP:$VERSION
                  echo "::set-output name=binary::${APP}-${VERSION}"
              env:
                  KAIKO_GCR_WRITER: ${{ secrets.KAIKO_GCR_WRITER }}
                  NODE_ENV: prod
                  SSR_HOST: preview-www.kaiko.com
                  SSR_PROTOCOL: https
                  STATIC_HOST: www.kaiko.com
                  STATIC_PROTOCOL: https
                  WP_URL: https://web-bo-i.kaiko.com/
                  API_UPLOADS_URL: https://web-bo-i.kaiko.com/wp-content/uploads
                  API_URL: https://web-bo-i.kaiko.com/wp-json/spin-api/
                  API_KEY: '-)<X[4J9Y!zxam;S'
                  WRANGLER_WORKER_NAME: website-institutional-prod
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: build/${{ steps.release.outputs.binary }}
            - name: Cleanup docker config
              if: always()
              run: rm -rf "$DOCKER_CONFIG"
